"""add checklist_requests and checklist_stages tables

Revision ID: 0d47d9e8148b
Revises: b376e5852f64
Create Date: 2026-08-13 13:32:11.271956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d47d9e8148b'
down_revision: Union[str, None] = 'b376e5852f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('request_number', sa.String(length=100), nullable=False),
    sa.Column('status_format', sa.String(length=255), nullable=False),
    sa.Column('is_last_stage', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number')
    )
    op.create_table('checklist_stages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('checklist_request_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('performed_remark', sa.Text(), nullable=False),
    sa.Column('approved_remark', sa.Text(), nullable=False),
    sa.Column('is_self_verified', sa.Boolean(), nullable=False),
    sa.Column('self_verification_details', sa.Text(), nullable=False),
    sa.Column('is_approvable', sa.Boolean(), nullable=False),
    sa.Column('is_last_stage', sa.Boolean(), nullable=False),
    sa.Column('submit_remarks', sa.Text(), nullable=False),
    sa.Column('self_approved_remark', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checklist_request_id'], ['checklist_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_stages_checklist_request_id'), 'checklist_stages', ['checklist_request_id'], unique=False)
    op.alter_column('format_stage_mappings', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('format_stage_mappings', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.drop_index('uq_format_stage_mappings', table_name='format_stage_mappings')
    op.alter_column('question_options', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('question_options', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('sections', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('sections', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.drop_index('ix_sections_fsm_id', table_name='sections')
    op.drop_constraint('sections_section_name_key', 'sections', type_='unique')
    op.create_index(op.f('ix_sections_format_stage_mapping_id'), 'sections', ['format_stage_mapping_id'], unique=False)
    op.alter_column('stage_question_mappings', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('stage_question_mappings', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.drop_index('ix_sqm_format_stage_mapping_id', table_name='stage_question_mappings')
    op.drop_index('ix_sqm_question_id', table_name='stage_question_mappings')
    op.drop_index('ix_sqm_sap_field_id', table_name='stage_question_mappings')
    op.drop_index('ix_sqm_section_id', table_name='stage_question_mappings')
    op.drop_index('uq_sqm_mapping_question', table_name='stage_question_mappings')
    op.create_index(op.f('ix_stage_question_mappings_format_stage_mapping_id'), 'stage_question_mappings', ['format_stage_mapping_id'], unique=False)
    op.create_index(op.f('ix_stage_question_mappings_question_id'), 'stage_question_mappings', ['question_id'], unique=False)
    op.create_index(op.f('ix_stage_question_mappings_sap_field_id'), 'stage_question_mappings', ['sap_field_id'], unique=False)
    op.create_index(op.f('ix_stage_question_mappings_section_id'), 'stage_question_mappings', ['section_id'], unique=False)
    op.alter_column('test_masters', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('test_masters', 'modified_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_masters', 'modified_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('test_masters', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.drop_index(op.f('ix_stage_question_mappings_section_id'), table_name='stage_question_mappings')
    op.drop_index(op.f('ix_stage_question_mappings_sap_field_id'), table_name='stage_question_mappings')
    op.drop_index(op.f('ix_stage_question_mappings_question_id'), table_name='stage_question_mappings')
    op.drop_index(op.f('ix_stage_question_mappings_format_stage_mapping_id'), table_name='stage_question_mappings')
    op.create_index('uq_sqm_mapping_question', 'stage_question_mappings', ['format_stage_mapping_id', 'question_id'], unique=True)
    op.create_index('ix_sqm_section_id', 'stage_question_mappings', ['section_id'], unique=False)
    op.create_index('ix_sqm_sap_field_id', 'stage_question_mappings', ['sap_field_id'], unique=False)
    op.create_index('ix_sqm_question_id', 'stage_question_mappings', ['question_id'], unique=False)
    op.create_index('ix_sqm_format_stage_mapping_id', 'stage_question_mappings', ['format_stage_mapping_id'], unique=False)
    op.alter_column('stage_question_mappings', 'modified_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('stage_question_mappings', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.drop_index(op.f('ix_sections_format_stage_mapping_id'), table_name='sections')
    op.create_unique_constraint('sections_section_name_key', 'sections', ['section_name'])
    op.create_index('ix_sections_fsm_id', 'sections', ['format_stage_mapping_id'], unique=False)
    op.alter_column('sections', 'modified_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('sections', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('question_options', 'modified_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('question_options', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.create_index('uq_format_stage_mappings', 'format_stage_mappings', ['format_id', 'stage_id'], unique=True)
    op.alter_column('format_stage_mappings', 'modified_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('format_stage_mappings', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.drop_index(op.f('ix_checklist_stages_checklist_request_id'), table_name='checklist_stages')
    op.drop_table('checklist_stages')
    op.drop_table('checklist_requests')
    # ### end Alembic commands ###
