"""add user_id and format_stage_mapping_id to checklist_stages

Revision ID: 172c6c0093eb
Revises: 92afe4196973
Create Date: 2026-08-13 14:10:53.505672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172c6c0093eb'
down_revision: Union[str, None] = '92afe4196973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_stages', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.add_column('checklist_stages', sa.Column('format_stage_mapping_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_checklist_stages_format_stage_mapping_id'), 'checklist_stages', ['format_stage_mapping_id'], unique=False)
    op.create_index(op.f('ix_checklist_stages_user_id'), 'checklist_stages', ['user_id'], unique=False)
    op.create_foreign_key(None, 'checklist_stages', 'format_stage_mappings', ['format_stage_mapping_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'checklist_stages', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checklist_stages', type_='foreignkey')
    op.drop_constraint(None, 'checklist_stages', type_='foreignkey')
    op.drop_index(op.f('ix_checklist_stages_user_id'), table_name='checklist_stages')
    op.drop_index(op.f('ix_checklist_stages_format_stage_mapping_id'), table_name='checklist_stages')
    op.drop_column('checklist_stages', 'format_stage_mapping_id')
    op.drop_column('checklist_stages', 'user_id')
    # ### end Alembic commands ###
