"""add_formats_master

Revision ID: 1e3f21bb5a7c
Revises: 90b44e38e24b
Create Date: 2026-08-06 17:41:04.337640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3f21bb5a7c'
down_revision: Union[str, None] = '90b44e38e24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('format_no', sa.String(length=100), nullable=False),
    sa.Column('format_title', sa.String(length=255), nullable=False),
    sa.Column('format_name', sa.String(length=255), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('format_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formats_format_no'), 'formats', ['format_no'], unique=True)
    op.create_index(op.f('ix_formats_format_type'), 'formats', ['format_type'], unique=False)
    op.create_index(op.f('ix_formats_unit_id'), 'formats', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formats_unit_id'), table_name='formats')
    op.drop_index(op.f('ix_formats_format_type'), table_name='formats')
    op.drop_index(op.f('ix_formats_format_no'), table_name='formats')
    op.drop_table('formats')
    # ### end Alembic commands ###
