"""add snip_layouts and snip_layout_columns

Revision ID: 498efd4ccafc
Revises: 172c6c0093eb
Create Date: 2026-09-18 12:16:04.269296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498efd4ccafc'
down_revision: Union[str, None] = '172c6c0093eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snip_layouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('format_stage_mapping_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['format_stage_mapping_id'], ['format_stage_mappings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('format_stage_mapping_id', 'section_id', name='uq_snip_layout_scope')
    )
    op.create_index(op.f('ix_snip_layouts_format_stage_mapping_id'), 'snip_layouts', ['format_stage_mapping_id'], unique=False)
    op.create_index(op.f('ix_snip_layouts_section_id'), 'snip_layouts', ['section_id'], unique=False)
    op.create_table('snip_layout_columns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snip_layout_id', sa.BigInteger(), nullable=False),
    sa.Column('header', sa.String(length=255), nullable=False),
    sa.Column('column_type', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('width', sa.String(length=30), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snip_layout_id'], ['snip_layouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snip_layout_columns_snip_layout_id'), 'snip_layout_columns', ['snip_layout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snip_layout_columns_snip_layout_id'), table_name='snip_layout_columns')
    op.drop_table('snip_layout_columns')
    op.drop_index(op.f('ix_snip_layouts_section_id'), table_name='snip_layouts')
    op.drop_index(op.f('ix_snip_layouts_format_stage_mapping_id'), table_name='snip_layouts')
    op.drop_table('snip_layouts')
    # ### end Alembic commands ###
