"""add checklist_stage_sections and stage_approval_label_mappings

Revision ID: 81e0ebea91c1
Revises: 0d47d9e8148b
Create Date: 2026-08-13 13:53:54.614912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e0ebea91c1'
down_revision: Union[str, None] = '0d47d9e8148b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_approval_label_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('checklist_stage_id', sa.BigInteger(), nullable=False),
    sa.Column('approval_label_id', sa.BigInteger(), nullable=False),
    sa.Column('remark_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('date_of_action', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.Column('is_refer_back', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_label_id'], ['approval_labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checklist_stage_id'], ['checklist_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remark_id'], ['remarks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_approval_label_mappings_approval_label_id'), 'stage_approval_label_mappings', ['approval_label_id'], unique=False)
    op.create_index(op.f('ix_stage_approval_label_mappings_checklist_stage_id'), 'stage_approval_label_mappings', ['checklist_stage_id'], unique=False)
    op.create_index(op.f('ix_stage_approval_label_mappings_remark_id'), 'stage_approval_label_mappings', ['remark_id'], unique=False)
    op.create_index(op.f('ix_stage_approval_label_mappings_role_id'), 'stage_approval_label_mappings', ['role_id'], unique=False)
    op.create_index(op.f('ix_stage_approval_label_mappings_user_id'), 'stage_approval_label_mappings', ['user_id'], unique=False)
    op.create_table('checklist_stage_sections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('checklist_stage_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checklist_stage_id'], ['checklist_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_stage_sections_checklist_stage_id'), 'checklist_stage_sections', ['checklist_stage_id'], unique=False)
    op.create_index(op.f('ix_checklist_stage_sections_section_id'), 'checklist_stage_sections', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_stage_sections_section_id'), table_name='checklist_stage_sections')
    op.drop_index(op.f('ix_checklist_stage_sections_checklist_stage_id'), table_name='checklist_stage_sections')
    op.drop_table('checklist_stage_sections')
    op.drop_index(op.f('ix_stage_approval_label_mappings_user_id'), table_name='stage_approval_label_mappings')
    op.drop_index(op.f('ix_stage_approval_label_mappings_role_id'), table_name='stage_approval_label_mappings')
    op.drop_index(op.f('ix_stage_approval_label_mappings_remark_id'), table_name='stage_approval_label_mappings')
    op.drop_index(op.f('ix_stage_approval_label_mappings_checklist_stage_id'), table_name='stage_approval_label_mappings')
    op.drop_index(op.f('ix_stage_approval_label_mappings_approval_label_id'), table_name='stage_approval_label_mappings')
    op.drop_table('stage_approval_label_mappings')
    # ### end Alembic commands ###
