"""add_units_master

Revision ID: 90b44e38e24b
Revises: 3a89f2a1928f
Create Date: 2026-08-06 15:18:46.541527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b44e38e24b'
down_revision: Union[str, None] = '3a89f2a1928f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'business_unit_id', name='uq_units_name_business_unit')
    )
    op.create_index(op.f('ix_units_business_unit_id'), 'units', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_name'), table_name='units')
    op.drop_index(op.f('ix_units_business_unit_id'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
