"""add approver_user_id and format_id to checklist_requests

Revision ID: 92afe4196973
Revises: f34ff179ba41
Create Date: 2026-08-13 14:06:52.256227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92afe4196973'
down_revision: Union[str, None] = 'f34ff179ba41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_requests', sa.Column('approver_user_id', sa.BigInteger(), nullable=True))
    op.add_column('checklist_requests', sa.Column('format_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_checklist_requests_approver_user_id'), 'checklist_requests', ['approver_user_id'], unique=False)
    op.create_index(op.f('ix_checklist_requests_format_id'), 'checklist_requests', ['format_id'], unique=False)
    op.create_foreign_key(None, 'checklist_requests', 'users', ['approver_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'checklist_requests', 'formats', ['format_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checklist_requests', type_='foreignkey')
    op.drop_constraint(None, 'checklist_requests', type_='foreignkey')
    op.drop_index(op.f('ix_checklist_requests_format_id'), table_name='checklist_requests')
    op.drop_index(op.f('ix_checklist_requests_approver_user_id'), table_name='checklist_requests')
    op.drop_column('checklist_requests', 'format_id')
    op.drop_column('checklist_requests', 'approver_user_id')
    # ### end Alembic commands ###
