"""add_approval_labels

Revision ID: 97429cd28c01
Revises: c139e058e3b9
Create Date: 2026-08-07 16:38:16.375874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97429cd28c01'
down_revision: Union[str, None] = 'c139e058e3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_labels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('stage_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_labels_label'), 'approval_labels', ['label'], unique=False)
    op.create_index(op.f('ix_approval_labels_stage_id'), 'approval_labels', ['stage_id'], unique=False)
    op.create_table('approval_label_user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('approval_label_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_label_id'], ['approval_labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_label_user_roles_approval_label_id'), 'approval_label_user_roles', ['approval_label_id'], unique=False)
    op.create_index(op.f('ix_approval_label_user_roles_role_id'), 'approval_label_user_roles', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_label_user_roles_role_id'), table_name='approval_label_user_roles')
    op.drop_index(op.f('ix_approval_label_user_roles_approval_label_id'), table_name='approval_label_user_roles')
    op.drop_table('approval_label_user_roles')
    op.drop_index(op.f('ix_approval_labels_stage_id'), table_name='approval_labels')
    op.drop_index(op.f('ix_approval_labels_label'), table_name='approval_labels')
    op.drop_table('approval_labels')
    # ### end Alembic commands ###
