"""add_is_validate_ad_to_users

Revision ID: a5aa03181478
Revises: 361f1a83e1ae
Create Date: 2026-06-17 15:35:26.548462

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a5aa03181478'
down_revision: str | None = '361f1a83e1ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add column with server_default=True for existing rows, then keep it as NOT NULL
    op.add_column('users', sa.Column('is_validate_ad', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_validate_ad')
    # ### end Alembic commands ###
