"""question_update_fields_and_junction

Revision ID: b376e5852f64
Revises: d5d2a7acb0ff
Create Date: 2026-08-07 17:53:14.850233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b376e5852f64'
down_revision: Union[str, None] = 'd5d2a7acb0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_sub_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('sub_question_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_sub_questions_question_id'), 'question_sub_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_sub_questions_sub_question_id'), 'question_sub_questions', ['sub_question_id'], unique=False)
    op.add_column('questions', sa.Column('has_multiple_text_box', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('questions', 'has_multiple_text_box', server_default=None)
    op.add_column('questions', sa.Column('validation_type_id', sa.BigInteger(), nullable=True))
    op.add_column('questions', sa.Column('parent_question_id', sa.BigInteger(), nullable=True))
    op.add_column('questions', sa.Column('master_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_questions_parent_question_id'), 'questions', ['parent_question_id'], unique=False)
    op.create_index(op.f('ix_questions_validation_type_id'), 'questions', ['validation_type_id'], unique=False)
    op.create_foreign_key(None, 'questions', 'questions', ['parent_question_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'questions', 'validation_types', ['validation_type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_validation_type_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_parent_question_id'), table_name='questions')
    op.drop_column('questions', 'master_type')
    op.drop_column('questions', 'parent_question_id')
    op.drop_column('questions', 'validation_type_id')
    op.drop_column('questions', 'has_multiple_text_box')
    op.drop_index(op.f('ix_question_sub_questions_sub_question_id'), table_name='question_sub_questions')
    op.drop_index(op.f('ix_question_sub_questions_question_id'), table_name='question_sub_questions')
    op.drop_table('question_sub_questions')
    # ### end Alembic commands ###
