"""remark_junction_table

Revision ID: c139e058e3b9
Revises: c341a3f3a4a3
Create Date: 2026-08-07 14:43:58.055158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c139e058e3b9'
down_revision: Union[str, None] = 'c341a3f3a4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remark_user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remark_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['remark_id'], ['remarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remark_user_roles_remark_id'), 'remark_user_roles', ['remark_id'], unique=False)
    op.create_index(op.f('ix_remark_user_roles_role_id'), 'remark_user_roles', ['role_id'], unique=False)
    op.drop_index('ix_remarks_role_id', table_name='remarks')
    op.drop_constraint('remarks_role_id_fkey', 'remarks', type_='foreignkey')
    op.drop_column('remarks', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remarks', sa.Column('role_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('remarks_role_id_fkey', 'remarks', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_remarks_role_id', 'remarks', ['role_id'], unique=False)
    op.drop_index(op.f('ix_remark_user_roles_role_id'), table_name='remark_user_roles')
    op.drop_index(op.f('ix_remark_user_roles_remark_id'), table_name='remark_user_roles')
    op.drop_table('remark_user_roles')
    # ### end Alembic commands ###
