"""add_questions_master

Revision ID: c172d7ba711a
Revises: 581d5e161204
Create Date: 2026-08-07 12:29:54.346930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c172d7ba711a'
down_revision: Union[str, None] = '581d5e161204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('answer_type', sa.String(length=50), nullable=False),
    sa.Column('has_text_box', sa.Boolean(), nullable=False),
    sa.Column('has_sub_question', sa.Boolean(), nullable=False),
    sa.Column('is_validation_required', sa.Boolean(), nullable=False),
    sa.Column('has_response_option', sa.Boolean(), nullable=False),
    sa.Column('allow_multiple_input', sa.Boolean(), nullable=False),
    sa.Column('has_associated_master', sa.Boolean(), nullable=False),
    sa.Column('is_calculated', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_title'), 'questions', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_title'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
