"""format_add_has_declaration_question

Revision ID: d5d2a7acb0ff
Revises: 97429cd28c01
Create Date: 2026-08-07 17:29:47.487062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d2a7acb0ff'
down_revision: Union[str, None] = '97429cd28c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('formats', sa.Column('has_declaration_question', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('formats', 'has_declaration_question', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formats', 'has_declaration_question')
    # ### end Alembic commands ###
