"""replace snip_layouts with templates and template_layout_columns

Revision ID: e6a4b5448808
Revises: 498efd4ccafc
Create Date: 2026-09-24 11:29:51.619738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6a4b5448808'
down_revision: Union[str, None] = '498efd4ccafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('format_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['format_id'], ['formats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_format_id'), 'templates', ['format_id'], unique=True)
    op.create_table('template_layout_columns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('format_stage_mapping_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.Column('header', sa.String(length=255), nullable=False),
    sa.Column('column_type', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('width', sa.String(length=30), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['format_stage_mapping_id'], ['format_stage_mappings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_layout_columns_format_stage_mapping_id'), 'template_layout_columns', ['format_stage_mapping_id'], unique=False)
    op.create_index(op.f('ix_template_layout_columns_section_id'), 'template_layout_columns', ['section_id'], unique=False)
    op.create_index(op.f('ix_template_layout_columns_template_id'), 'template_layout_columns', ['template_id'], unique=False)
    op.drop_index('ix_snip_layout_columns_snip_layout_id', table_name='snip_layout_columns')
    op.drop_table('snip_layout_columns')
    op.drop_index('ix_snip_layouts_format_stage_mapping_id', table_name='snip_layouts')
    op.drop_index('ix_snip_layouts_section_id', table_name='snip_layouts')
    op.drop_table('snip_layouts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snip_layouts',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('snip_layouts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('format_stage_mapping_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('modified_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['format_stage_mapping_id'], ['format_stage_mappings.id'], name='snip_layouts_format_stage_mapping_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name='snip_layouts_section_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='snip_layouts_pkey'),
    sa.UniqueConstraint('format_stage_mapping_id', 'section_id', name='uq_snip_layout_scope'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_snip_layouts_section_id', 'snip_layouts', ['section_id'], unique=False)
    op.create_index('ix_snip_layouts_format_stage_mapping_id', 'snip_layouts', ['format_stage_mapping_id'], unique=False)
    op.create_table('snip_layout_columns',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('snip_layout_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('header', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('column_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('width', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('modified_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['snip_layout_id'], ['snip_layouts.id'], name='snip_layout_columns_snip_layout_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='snip_layout_columns_pkey')
    )
    op.create_index('ix_snip_layout_columns_snip_layout_id', 'snip_layout_columns', ['snip_layout_id'], unique=False)
    op.drop_index(op.f('ix_template_layout_columns_template_id'), table_name='template_layout_columns')
    op.drop_index(op.f('ix_template_layout_columns_section_id'), table_name='template_layout_columns')
    op.drop_index(op.f('ix_template_layout_columns_format_stage_mapping_id'), table_name='template_layout_columns')
    op.drop_table('template_layout_columns')
    op.drop_index(op.f('ix_templates_format_id'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
