"""add question_answers question_answer_helpers and junction table

Revision ID: f34ff179ba41
Revises: 81e0ebea91c1
Create Date: 2026-08-13 14:02:41.645885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34ff179ba41'
down_revision: Union[str, None] = '81e0ebea91c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_answer_helpers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('text_box_value', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('checklist_stage_id', sa.BigInteger(), nullable=False),
    sa.Column('checklist_stage_section_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.Column('question_option_id', sa.BigInteger(), nullable=True),
    sa.Column('receiver_user_id', sa.BigInteger(), nullable=True),
    sa.Column('response_question_option_id', sa.BigInteger(), nullable=True),
    sa.Column('stage_question_mapping_id', sa.BigInteger(), nullable=True),
    sa.Column('textbox_value', sa.Text(), nullable=False),
    sa.Column('response_answer', sa.String(length=100), nullable=False),
    sa.Column('comma_separated_name', sa.Text(), nullable=False),
    sa.Column('has_helper', sa.Boolean(), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('sub_answer_serial_no', sa.String(length=100), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_title', sa.String(length=255), nullable=False),
    sa.Column('sample_vails', sa.String(length=255), nullable=False),
    sa.Column('answer_total_vails', sa.Integer(), nullable=False),
    sa.Column('issued_by_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_by_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issuer_name', sa.String(length=255), nullable=False),
    sa.Column('is_issued_vails', sa.Boolean(), nullable=False),
    sa.Column('has_vails', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checklist_stage_id'], ['checklist_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checklist_stage_section_id'], ['checklist_stage_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_option_id'], ['question_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_question_option_id'], ['question_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_question_mapping_id'], ['stage_question_mappings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_answers_checklist_stage_id'), 'question_answers', ['checklist_stage_id'], unique=False)
    op.create_index(op.f('ix_question_answers_checklist_stage_section_id'), 'question_answers', ['checklist_stage_section_id'], unique=False)
    op.create_index(op.f('ix_question_answers_product_id'), 'question_answers', ['product_id'], unique=False)
    op.create_index(op.f('ix_question_answers_question_id'), 'question_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_answers_question_option_id'), 'question_answers', ['question_option_id'], unique=False)
    op.create_index(op.f('ix_question_answers_receiver_user_id'), 'question_answers', ['receiver_user_id'], unique=False)
    op.create_index(op.f('ix_question_answers_response_question_option_id'), 'question_answers', ['response_question_option_id'], unique=False)
    op.create_index(op.f('ix_question_answers_stage_question_mapping_id'), 'question_answers', ['stage_question_mapping_id'], unique=False)
    op.create_table('question_answer_sub_question_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_answer_id', sa.BigInteger(), nullable=False),
    sa.Column('question_answer_helper_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_answer_helper_id'], ['question_answer_helpers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_answer_id'], ['question_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_answer_sub_question_answers_question_answer_helper_id'), 'question_answer_sub_question_answers', ['question_answer_helper_id'], unique=False)
    op.create_index(op.f('ix_question_answer_sub_question_answers_question_answer_id'), 'question_answer_sub_question_answers', ['question_answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_answer_sub_question_answers_question_answer_id'), table_name='question_answer_sub_question_answers')
    op.drop_index(op.f('ix_question_answer_sub_question_answers_question_answer_helper_id'), table_name='question_answer_sub_question_answers')
    op.drop_table('question_answer_sub_question_answers')
    op.drop_index(op.f('ix_question_answers_stage_question_mapping_id'), table_name='question_answers')
    op.drop_index(op.f('ix_question_answers_response_question_option_id'), table_name='question_answers')
    op.drop_index(op.f('ix_question_answers_receiver_user_id'), table_name='question_answers')
    op.drop_index(op.f('ix_question_answers_question_option_id'), table_name='question_answers')
    op.drop_index(op.f('ix_question_answers_question_id'), table_name='question_answers')
    op.drop_index(op.f('ix_question_answers_product_id'), table_name='question_answers')
    op.drop_index(op.f('ix_question_answers_checklist_stage_section_id'), table_name='question_answers')
    op.drop_index(op.f('ix_question_answers_checklist_stage_id'), table_name='question_answers')
    op.drop_table('question_answers')
    op.drop_table('question_answer_helpers')
    # ### end Alembic commands ###
